version: '2'
services:
    marketing-app:
        image: marketing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://marketing-mysql:3306/marketing?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    marketing-mysql:
        extends:
            file: mysql.yml
            service: marketing-mysql
